import './style.css';

const icons = {
  chat: '▢', memory: '♧', books: '▤', profile: '♙', letter: '✉', music: '♫', settings: '⚙', send: '↑', plus: '+', search: '⌕', back: '‹', spark: '✦'
};

const storage = {
  get(key, fallback) { try { return JSON.parse(localStorage.getItem(`luma:${key}`)) ?? fallback; } catch { return fallback; } },
  set(key, value) { localStorage.setItem(`luma:${key}`, JSON.stringify(value)); }
};

const state = {
  page: 'home',
  characters: storage.get('characters', [{ id: 'lumi', name: 'Lumi', role: '你的溫柔同行者', greeting: '我在這裡。今天想讓我陪你整理什麼心情？', avatar: 'L', color: '#abc6e6', prompt: '你是 Lumi，一位溫柔、細膩並尊重使用者界線的陪伴者。請以繁體中文回覆。' }]),
  memories: storage.get('memories', [{ id: 1, title: '初次相遇', detail: '我們約定在這裡慢慢認識彼此。', tag: '關係', pinned: true }, { id: 2, title: '喜歡的時刻', detail: '安靜聽歌、下雨天和深夜聊天。', tag: '偏好', pinned: false }]),
  profile: storage.get('profile', { name: '旅人', pronouns: '你／妳', note: '喜歡被溫柔地傾聽。' }),
  messages: storage.get('messages', []),
  api: storage.get('api', { url: '', key: '', model: '' }),
};
let activeCharacter = state.characters[0];

function save() { ['characters','memories','profile','messages','api'].forEach((key) => storage.set(key, state[key])); }
function esc(value = '') { const el = document.createElement('div'); el.textContent = value; return el.innerHTML; }
function navItem(page, icon, label) { return `<button class="nav-item ${state.page === page ? 'active' : ''}" data-page="${page}"><i>${icons[icon]}</i><span>${label}</span></button>`; }
function shell(content) { return `<main class="app-shell"><aside class="rail"><div class="brand">L<span>u</span>ma</div>${navItem('home','spark','桌面')}${navItem('chat','chat','對話')}${navItem('memory','memory','記憶')}${navItem('books','books','角色')}${navItem('profile','profile','我')}<div class="rail-bottom">${navItem('settings','settings','設定')}</div></aside><section class="content">${content}</section><nav class="mobile-nav">${navItem('home','spark','桌面')}${navItem('chat','chat','對話')}${navItem('memory','memory','記憶')}${navItem('books','books','角色')}${navItem('profile','profile','我')}</nav></main>`; }
function home() { const now = new Date(); const time = now.toLocaleTimeString('zh-TW',{hour:'2-digit', minute:'2-digit',hour12:false}); const date = now.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',weekday:'long'}); return shell(`<header class="topbar"><button class="round menu">☰</button><h1>Home</h1><button class="round">♧</button></header><div class="home"><p class="date">${date}</p><div class="clock">${time}</div><section class="quick-grid"><button data-page="chat"><b>${icons.chat}</b>對話</button><button data-page="memory"><b>${icons.memory}</b>記憶</button><button data-page="books"><b>${icons.books}</b>角色</button><button data-page="profile"><b>${icons.letter}</b>信箱</button></section><section class="calendar-card glass"><div><small>${now.getFullYear()}</small><h2>${now.toLocaleDateString('en-US',{month:'long'})}</h2><p>${now.toLocaleDateString('en-US',{weekday:'long'})}</p></div><div class="calendar-orb">${now.toLocaleDateString('en-US',{weekday:'short'}).slice(0,1)}</div><div class="days">S　M　T　W　T　F　S<br>　　1　2　3　4　5<br>6　7　8　9　10　11　12<br>13　14　15　16　17　18　19</div></section><section class="music-card glass"><div class="record">♫</div><div><small>MUSIC</small><h2>Music</h2><p>尚未添加音樂</p><div class="progress"><i></i></div></div><button class="play">▶</button></section></div>`); }
function chat() { const chatMessages = state.messages.length ? state.messages : [{role:'assistant',content:activeCharacter.greeting}]; return shell(`<header class="page-head"><div><span class="eyebrow">PRIVATE SPACE</span><h1>${esc(activeCharacter.name)}</h1><p>${esc(activeCharacter.role)}</p></div><div class="avatar" style="--avatar:${activeCharacter.color}">${esc(activeCharacter.avatar)}</div></header><div class="chat-layout"><aside class="chat-list glass"><button class="new-chat" id="new-chat">${icons.plus} 開啟新對話</button><p class="section-label">角色</p>${state.characters.map(c=>`<button class="character ${c.id===activeCharacter.id?'selected':''}" data-character="${c.id}"><span class="mini-avatar" style="--avatar:${c.color}">${esc(c.avatar)}</span><span>${esc(c.name)}<small>${esc(c.role)}</small></span></button>`).join('')}<p class="section-label">這段對話</p><button class="tiny-action" id="summarize">${icons.spark} 產生對話摘要</button></aside><section class="conversation"><div class="memory-strip"><span>${icons.memory}</span><div><b>共同記憶已啟用</b><small>${state.memories.filter(m=>m.pinned).map(m=>esc(m.title)).join('、') || '尚未釘選記憶'}</small></div><button data-page="memory">管理</button></div><div class="messages" id="messages">${chatMessages.map(messageTemplate).join('')}</div><form class="composer" id="composer"><button type="button" class="attach" title="附件">＋</button><textarea id="message-input" placeholder="寫下想對 ${esc(activeCharacter.name)} 說的話…" rows="1"></textarea><button class="send" title="送出">${icons.send}</button></form><p class="disclaimer">AI 回覆可能出錯；請避免在此儲存極度敏感的個人資料。</p></section></div>`); }
function messageTemplate(m) { return `<article class="message ${m.role}"><div class="message-avatar">${m.role==='assistant'?esc(activeCharacter.avatar):esc(state.profile.name).slice(0,1)}</div><div class="bubble">${esc(m.content).replace(/\n/g,'<br>')}<time>${m.time || ''}</time>${m.role==='user'?`<button class="to-memory" data-memory="${esc(m.content)}">${icons.memory} 記為回憶</button>`:''}</div></article>`; }
function memory() { return shell(`<header class="page-head"><div><span class="eyebrow">OUR ARCHIVE</span><h1>記憶庫</h1><p>收好我們每一次靠近的證明。</p></div><button class="primary" id="add-memory">${icons.plus} 新增記憶</button></header><section class="archive"><div class="archive-tools"><label>${icons.search}<input placeholder="搜尋回憶" id="memory-search"></label><span>${state.memories.length} 段回憶</span></div><div class="memory-grid" id="memory-grid">${memoriesTemplate()}</div></section>`); }
function memoriesTemplate(filter='') { return state.memories.filter(m=>`${m.title}${m.detail}${m.tag}`.toLowerCase().includes(filter.toLowerCase())).map(m=>`<article class="memory-card glass"><div class="memory-card-top"><span class="tag">${esc(m.tag)}</span><button class="pin ${m.pinned?'on':''}" data-pin="${m.id}">✦</button></div><h2>${esc(m.title)}</h2><p>${esc(m.detail)}</p><footer><span>${m.pinned?'已帶入對話':'僅保存'}</span><button data-delete-memory="${m.id}">刪除</button></footer></article>`).join('') || '<p class="empty">沒有找到符合的回憶。</p>'; }
function books() { return shell(`<header class="page-head"><div><span class="eyebrow">CHARACTER LIBRARY</span><h1>角色書</h1><p>讓每一位重要的人都有自己的故事。</p></div><div><button class="secondary" id="import-char">匯入角色卡</button> <button class="primary" id="add-char">${icons.plus} 建立角色</button></div></header><section class="character-grid">${state.characters.map(c=>`<article class="character-card glass"><div class="character-cover" style="--avatar:${c.color}"><span>${esc(c.avatar)}</span></div><div><span class="tag">角色</span><h2>${esc(c.name)}</h2><p>${esc(c.role)}</p><button class="text-button" data-edit-char="${c.id}">編輯設定 →</button></div></article>`).join('')}</section><input id="char-file" type="file" accept="application/json,.json,.png" hidden>`); }
function profile() { const p=state.profile; return shell(`<header class="page-head"><div><span class="eyebrow">ABOUT YOU</span><h1>個人檔案</h1><p>你希望被如何認識與珍惜。</p></div></header><form class="profile-form glass" id="profile-form"><label>顯示名稱<input name="name" value="${esc(p.name)}" placeholder="你的名字"></label><label>稱呼／人稱<input name="pronouns" value="${esc(p.pronouns)}" placeholder="例如：你／妳"></label><label class="wide">想讓角色知道的事<textarea name="note" rows="5" placeholder="你的喜好、界線或希望被怎麼陪伴…">${esc(p.note)}</textarea></label><div class="wide form-actions"><button class="primary">儲存個人檔案</button></div></form>`); }
function settings() { const a=state.api; return shell(`<header class="page-head"><div><span class="eyebrow">CONNECTION</span><h1>AI 連線設定</h1><p>以 OpenAI 相容 API 連接你選擇的模型服務。</p></div></header><form class="profile-form glass" id="api-form"><label class="wide">API Base URL<input name="url" value="${esc(a.url)}" placeholder="https://api.example.com/v1"></label><label class="wide">API Key<input type="password" name="key" value="${esc(a.key)}" placeholder="只儲存在這台裝置的瀏覽器中"></label><label class="wide">模型名稱<input name="model" value="${esc(a.model)}" placeholder="例如：gpt-4o-mini"></label><p class="form-hint wide">此版本會把設定保存在瀏覽器本機。GitHub Pages 沒有安全的伺服器端金鑰保存空間，請只使用你信任的 API 服務。</p><div class="wide form-actions"><button class="primary">儲存連線設定</button></div></form>`); }
function render(){ const pages={home,chat,memory,books,profile,settings}; document.querySelector('#app').innerHTML=pages[state.page](); bind(); }
function bind(){ document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render();}); document.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>{activeCharacter=state.characters.find(c=>c.id===b.dataset.character);render();}); document.querySelector('#composer')?.addEventListener('submit',sendMessage); document.querySelectorAll('.to-memory').forEach(b=>b.onclick=()=>addMemory('對話片段',b.dataset.memory,'對話')); document.querySelector('#add-memory')?.addEventListener('click',()=>{const title=prompt('記憶標題'); if(title){const detail=prompt('記憶內容')||'';addMemory(title,detail,'手動');}}); document.querySelector('#memory-search')?.addEventListener('input',(e)=>document.querySelector('#memory-grid').innerHTML=memoriesTemplate(e.target.value)); document.querySelectorAll('[data-pin]').forEach(b=>b.onclick=()=>{const m=state.memories.find(x=>x.id===Number(b.dataset.pin));m.pinned=!m.pinned;save();render();}); document.querySelectorAll('[data-delete-memory]').forEach(b=>b.onclick=()=>{state.memories=state.memories.filter(x=>x.id!==Number(b.dataset.deleteMemory));save();render();}); document.querySelector('#profile-form')?.addEventListener('submit',saveProfile); document.querySelector('#api-form')?.addEventListener('submit',saveApi); document.querySelector('#add-char')?.addEventListener('click',()=>editCharacter()); document.querySelectorAll('[data-edit-char]').forEach(b=>b.onclick=()=>editCharacter(state.characters.find(c=>c.id===b.dataset.editChar))); document.querySelector('#import-char')?.addEventListener('click',()=>document.querySelector('#char-file').click()); document.querySelector('#char-file')?.addEventListener('change',importCharacter); document.querySelector('#new-chat')?.addEventListener('click',()=>{state.messages=[];save();render();}); }
function addMemory(title,detail,tag){state.memories.unshift({id:Date.now(),title,detail,tag,pinned:true});save();if(state.page==='memory')render();}
function saveProfile(e){e.preventDefault();state.profile=Object.fromEntries(new FormData(e.target));save();alert('個人檔案已儲存。');render();}
function saveApi(e){e.preventDefault();state.api=Object.fromEntries(new FormData(e.target));save();alert('連線設定已儲存。');}
function editCharacter(existing){const name=prompt('角色名稱',existing?.name||'');if(!name)return; const role=prompt('角色定位／簡介',existing?.role||'');const promptText=prompt('角色系統提示詞',existing?.prompt||''); const c=existing||{id:Date.now().toString(),avatar:name.slice(0,1),color:'#abc6e6',greeting:'很高興在這裡遇見你。'};Object.assign(c,{name,role:role||'',prompt:promptText||''});if(!existing)state.characters.push(c);save();render();}
function importCharacter(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);const card=data.data||data;state.characters.push({id:Date.now().toString(),name:card.name||'未命名角色',role:card.description?.slice(0,80)||'匯入角色',greeting:card.first_mes||'你好。',prompt:card.personality||card.description||'',avatar:(card.name||'R').slice(0,1),color:'#b8c8e8'});save();render();alert('角色卡已匯入。');}catch{alert('無法讀取此角色卡檔案。請選擇 JSON 格式。');}};reader.readAsText(file);}
async function sendMessage(e){e.preventDefault();const input=document.querySelector('#message-input');const content=input.value.trim();if(!content)return;state.messages.push({role:'user',content,time:new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})});input.value='';save();render();if(!state.api.url||!state.api.key||!state.api.model){state.messages.push({role:'assistant',content:'我已收到你的話。要讓我真正回覆，請先到「設定」填入 OpenAI 相容 API 的 URL、金鑰與模型名稱。',time:'現在'});save();render();return;}try{const context=state.memories.filter(m=>m.pinned).map(m=>`- ${m.title}: ${m.detail}`).join('\n');const response=await fetch(`${state.api.url.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${state.api.key}`},body:JSON.stringify({model:state.api.model,messages:[{role:'system',content:`${activeCharacter.prompt}\n\n使用者資料：${state.profile.name}，${state.profile.note}\n共同記憶：\n${context}`},...state.messages.map(({role,content})=>({role,content}))]})});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'API 請求失敗');state.messages.push({role:'assistant',content:data.choices?.[0]?.message?.content||'沒有收到可顯示的回覆。',time:'現在'});}catch(error){state.messages.push({role:'assistant',content:`連線失敗：${error.message}`,time:'現在'});}save();render();}
render();
